### ISSUE TITLE
Need Changes

### ISSUE THREAD

**Issue by prem-narain** [artifacia/libsdae#1]
First Change: 

Change **README.md** Installation link with

`https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#pip-installation`

Second Change:

Change **requirements.txt** tensorflow link with  **tensorflow** while trying to install modules giving error
 `tensorflow-0.7.1-cp34-none-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by rajarsheem** [comment]
Regarding the 1st point, I have updated the README.

For the 2nd point, I believe, somehow, your system architecture is not supporting TF. Can you throw some light on your configuration ?

**Comment by prem-narain** [comment]
Yes you are right about second issue tensorflow is not installed globally in my system.I just checked my system configuration. Thanks +1:
